### PR TITLE
Trim username only when it looks like an email

### PR DESCRIPTION
**Pull request by luisrudge**
fix https://github.com/auth0/lock/issues/1537

### Changes
Instead of always trimming the username, we'll only trim when the username looks like an email.

### References

https://github.com/auth0/lock/issues/1537

### Testing

* [X] This change adds unit test coverage

### CODE REVIEW

**Comment by luisrudge** [comment]
We'll do this in another way

**Comment by cocojoe** [comment]
@luisrudge can you reference the alternative PR please, helps anyone originally following. Thanks

**Comment by luisrudge** [comment]
https://github.com/auth0/lock/pull/1541

**Comment by cocojoe** [comment]
@luisrudge you just referenced the same PR...

**Comment by luisrudge** [comment]
😝 sorry. https://github.com/auth0/lock/pull/1546

**Pull request closed without merging**
