### PR TITLE
Welcome logo - added text alternative

### PR DESCRIPTION
**Pull request by piwysocki**
### Changes

In Welcome component added alt="Logo" to img.

It's an accessibility issue: The text alternative is missing for that image, so screen reader users won't be able to understand the purpose of the image.

### References

To adhere to the WCAG Rule: 1.1.1.b Alternative Text (Informative Images)- Images that convey content MUST have programmatically-discernible alternative text.

### Testing

* [ ] This change adds unit test coverage
* [ ] This change adds integration test coverage
* [x] This change has been tested on the latest version of the platform/language

### Checklist

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] All code quality tools/guidelines have been run/followed
* [x] All relevant assets have been compiled

### CODE REVIEW

**Comment by pbuckleyfen** [comment]
Agreed. People who are blind cannot see images on a page. In order to give people who cannot see an image access to the information conveyed by the image, it must have a text alternative. The text alternative must describe the information or function represented by the image. Screen readers can then use the alternative text to convey that information to the screen reader user. 

Without adding configuration, adding the alt text " logo" is the best solution here

**Review by frederikprijck — CHANGES_REQUESTED** [review]
Thanks for the PR. As mentioned before, please know opening issues to discuss this is recommended.

I can see you used `Logo` as the alt text, but the image is not always going to be a logo so we will need some other text that accurately describes the image.

On top of that, we use i18n, so we should not hard-code the alt text to ensure it translate correctly for all users. Additionally, we need to provide the alt text for all the available languages.

Happy to review the PR if the above is resolved.

**Comment by piwysocki** [comment]
added translation for "Logo" text

**Review by frederikprijck — COMMENTED** [review]
Thanks for making the changes.

However, we have explicitly set `alt` to an empty string to make it hidden for screen readers, see https://www.w3.org/WAI/tutorials/images/tips/:

> If you use a null (empty) text alternative (alt="") to hide decorative images, make sure that there is no space character in between the quotes. If a space character is present, the image may not be effectively hidden from assistive technologies. For instance, some screen readers will still announce the presence of an image if a space character is put between the quotes.

Based on that, we should keep the `alt=""` as logo images have no content meaning and should not be informed to users using a screen reader.

Apologies, I should have caught this before asking to add the i18n changes, however, that's why we ask to open issues first. 

Based on that, I believe we should not merge this and leave it as is.

**Comment by piwysocki** [comment]
why don't we make a combination of both alt="logo" and aria-hidden="true" ?

**Comment by frederikprijck** [comment]
We'd be sending along additional bytes to the user for something that won't and shouldn't be used to begin with.

On top of that, https://www.w3.org/WAI/tutorials/images/decorative/ mentions using `alt=""`, not `aria-hidden`. Even though aria-hidden is useful, for images you want to rely on `alt=""` instead.

**Pull request closed without merging**
