### PR TITLE
WelcomeMessage header text marked as heading

### PR DESCRIPTION
**Pull request by piwysocki**
### Changes

role="heading" attribute and aria-level="1" attribute added to WelcomeMessage heading.

It adds heading semantics to markup without the risk of breaking any styles.

### References

This change resolves an issue in accessibility.
Header name and title appears to be heading for section of content, but is not marked as heading for screen reader users.

### Testing

* [ ] This change adds unit test coverage
* [ ] This change adds integration test coverage
* [x] This change has been tested on the latest version of the platform/language

### Checklist

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] All code quality tools/guidelines have been run/followed
* [x] All relevant assets have been compiled

### CODE REVIEW

**Comment by frederikprijck** [comment]
Thanks for the PR, can you elaborate which tool showed this as an a11y issue to try and understand what's happening and how a welcome message is treated as a heading?

Thanks

**Comment by pbuckleyfen** [comment]
Hey, as outlined in rule 1.3.1.e Headings - Text that acts as a heading visually or structurally MUST be designated as a true heading in the markup.

The Welcome message visually acts as the main element heading on the login screen.

Providing a heading element will aid screen reader users to understand the structure of the content

**Comment by piwysocki** [comment]
More info provided above

**Comment by frederikprijck** [comment]
Thanks for this change, looks legit and definetly want to look into adding this.

Has this been tester with a certain screenreader?

**Review by frederikprijck — APPROVED** [review]

**Comment by stevehobbsdev** [comment]
Thanks for your contribution here @piwysocki ! 🎉

**Pull request merged**
