### PR TITLE
Afrikaans Lang Update

### PR DESCRIPTION
**Pull request by jdunhin**
Sorry there was some mistakes.

### CODE REVIEW

**Comment by luisrudge** [comment]
can you please rebase with master? I think you got the old version

**Comment by jdunhin** [comment]
Sorry but how do i rebase?

**Comment by luisrudge** [comment]
I updated your PR so you don't have to rebase anymore. I kept a few words and the old placeholder email. Can you take a look and see if it makes sense?

**Comment by jdunhin** [comment]
Awesome thank you. Will this Afrikaans Lang Update #1053 what i did 4 days ago also show. Sorry dumb with this.

**Comment by luisrudge** [comment]
Yeah.. I updated the previous PR you sent with this one, but I didn't use all the changes, because you changed the placeholder email address and removed the Welcome message, for example. I ended up using some changes you made, but not all of them.

**Comment by jdunhin** [comment]
Ok the important changes was(Upadate af.js  …			288839a):
if we can push this one all will be good. 
` signupTitle: 'Registreer',
 -  signUpLabel: 'Teken in',		 +  signUpLabel: 'Registreer',
 -  signUpSubmitLabel: 'Teken in',		 +  signUpSubmitLabel: 'Registreer',
    signUpTerms: '',		    signUpTerms: '',
 -  signUpWithLabel: 'Teken in met %s',		 +  signUpWithLabel: 'Registreer met %s',`

**Comment by luisrudge** [comment]
Cool. Thank you 🎉

**Comment by jdunhin** [comment]
Thank you, I see these changes are not updated. https://github.com/auth0/lock/commit/288839ad6d2b563d0514c841e357e213e20d30b7

Wil send pr again.

**Comment by luisrudge** [comment]
I'm so sorry. I think I misunderstood your comment. Please clone this project again and open a new PR so we don't have any conflicts in the files.

**Pull request merged**
