### PR TITLE
Show which loaders to install in README

### PR DESCRIPTION
**Pull request by ianks**

### CODE REVIEW

**Comment by gnandretta** [comment]
Thanks! I've already merged #251 which documents needed loaders in the README and improves the webpack example.

**Comment by ianks** [comment]
@gnandretta That example is still wrong. It needs to be `loader` singular for the first one.

**Comment by ianks** [comment]
you could cherry pick https://github.com/ianks/lock/commit/6296c9616cbca6116f1e0444f7eb414041402d53 for that.

**Comment by gnandretta** [comment]
@ianks The commit ianks@86a75dc is outdated. It should be fixed in the README now.

**Pull request closed without merging**
