### PR TITLE
Add `showTerms` option

### PR DESCRIPTION
**Pull request by luisrudge**
Add `showTerms` option to show/hide terms string in the signup page

### CODE REVIEW

**Comment by cocojoe** [comment]
Add description, why are we making this change? Should add screenshots as it will change the default display behaviour with the additional box.

**Comment by luisrudge** [comment]
@cocojoe updated

**Comment by cocojoe** [comment]
@luisrudge what happens if `showterms` is `false` but `mustAcceptTerms` is `true`?

**Comment by luisrudge** [comment]
Doesn’t show the terms Because if you have to manually set showTerms to false

Luís
________________________________

**Comment by cocojoe** [comment]
OK that seems fair as the user has explicitly disabled them.

**Pull request merged**
