### PR TITLE
Add Slovenian translations

### PR DESCRIPTION
**Pull request by jogee**

### CODE REVIEW

**Comment by luisrudge** [comment]
Thanks again! 🎉

**Comment by urosgruber** [comment]
If this is Slovenian language then I must be from other planet. Can you please revert this as it doesn't make any sense.

**Comment by urosgruber** [comment]
Actually Romanian and Slovenia files are named in wrong way.

**Comment by luisrudge** [comment]
@urosgruber did you check this PR? https://github.com/auth0/lock/pull/1092

**Comment by urosgruber** [comment]
@luisrudge no, but looks like all good now.

**Pull request merged**
