### PR TITLE
Correcting callbackUrl to be redirectUrl

### PR DESCRIPTION
**Pull request by leog**
According to the Lock 9 to Lock 10 migration doc the `callbackUrl` was renamed to `redirectUrl`.

### CODE REVIEW

**Comment by hzalaz** [comment]
Thanks for the PR!

**Comment by johnlim** [comment]
Should/will `redirectUrl` be renamed to `redirectUri` so that its consistent with auth0.js V8?

**Comment by luisrudge** [comment]
That would break a lot of users, so maybe in the next major version.

**Comment by johnlim** [comment]
@luisrudge thanks! looking forward to it.

**Pull request merged**
