### PR TITLE
Release v10.20.0

### PR DESCRIPTION
**Pull request by luisrudge**

### CODE REVIEW

**Comment by justinclift** [comment]
Just to check, is this ok to use in production?

Asking because the "Releases" page in this GitHub repo is still saying 10.18 is the latest release. :smile:

**Comment by luisrudge** [comment]
Hi! Yes. Not sure why our automated release didn't publish the releases to github.. I'll check on Monday. But you can use 10.20.0 in production 🎉

**Comment by justinclift** [comment]
Thanks @luisrudge. :smile:

**Comment by luisrudge** [comment]
ahaha. thanks. I'll look into it

**Comment by justinclift** [comment]
Reminder ping for this. :wink:

**Comment by luisrudge** [comment]
ofc I forgot 😝 I'll ping the responsible human right now. He'll get back to me tomorrow

**Pull request merged**
