### PR TITLE
Update to React 16

### PR DESCRIPTION
**Pull request by bureson**
### Changes

- Update React and ReactDOM dependencies from version `^15.6.2` to `^16.6.3`

### References

- React 15.x.x contains code that behaves funky and generally it is nice to stay up to date with dependencies

### Testing

* [ ] This change adds unit test coverage
* [ ] This change adds integration test coverage
* [ ] This change has been tested on the latest version of the platform/language

### Checklist

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [ ] All existing and new tests complete without errors
* [x] All code quality tools/guidelines have been run/followed
* [x] All relevant assets have been compiled
* [x] All active GitHub checks have passed

### CODE REVIEW

**Comment by luisrudge** [comment]
We'll do that in the next major. There's more context here: https://github.com/auth0/lock/pull/1142#issue-146055423

**Comment by bureson** [comment]
@luisrudge Thanks for reply! Can I just ask when it the next major expected to be released?

**Comment by luisrudge** [comment]
No ETA. Probably Q1 2019.

**Comment by jbojcic1** [comment]
Hi @luisrudge. What's the status of this? Can we expect it anytime soon?

**Comment by luisrudge** [comment]
Hi @jbojcic1. No news on this front yet. I'd say you shouldn't expect a new major anytime soon.

**Comment by cscleison** [comment]
@jbojcic1 if you pay for this product, i would recommend you to send an email to sales as we did... 
come on guys, react 16 was released in 2017!

**Comment by petrogad** [comment]
This is pretty frustrating, we pay for Auth0 and have an additional bundle of React now in our package.

**Comment by luisrudge** [comment]
Hi folks 👋  I wrote a more contextual response here: https://github.com/auth0/lock/issues/1722#issuecomment-526700308

**Pull request closed without merging**
