### PR TITLE
fix(i18n): use 您 for consistency

### PR DESCRIPTION
**Pull request by blackwindforce**

### CODE REVIEW

**Comment by luisrudge** [comment]
Can you explain what this change does?

**Comment by blackwindforce** [comment]
This change uses formal "you" in Chinese, and keep using it consistently.

**Comment by zachguo** [comment]
@luisrudge 您 is politer than 你, and is usually used in formal and written articulation.
@blackwindforce Can you please also do the same for the simplified Chinese file?

**Comment by luisrudge** [comment]
Thanks for the PR 🎉

**Pull request merged**
