### PR TITLE
fixing react-addons-css-transition-group issue

### PR DESCRIPTION
**Pull request by eoinmurray**
Trying to fix https://github.com/auth0/lock/issues/994

removing react-addons-css-transition-group and adding react-transition-group

### CODE REVIEW

**Comment by eoinmurray** [comment]
Would be great if this could be merged and released.

**Comment by luisrudge** [comment]
Thanks for the PR! I'll review this in a couple of days. The next release is scheduled for the 22th.

**Comment by noah79** [comment]
Is this really so hard to fix and get merged in?

**Comment by luisrudge** [comment]
Thanks for the PR 🎉 The next release was a bit delayed and will probably happen next Monday.

**Pull request merged**
