### PR TITLE
fix "Uncaught TypeError: Cannot read property 'getIn' of undefined"

### PR DESCRIPTION
**Pull request by UnsungHero97**
fix for https://github.com/auth0/lock/issues/1090, https://github.com/auth0/lock/issues/907

### CODE REVIEW

**Comment by luisrudge** [comment]
Hi @UnsungHero97 can you take a look on those failing tests?

**Comment by UnsungHero97** [comment]
@luisrudge, I looked at it, made a minor change, and the tests are now passing.

**Comment by luisrudge** [comment]
Thanks! I'm not super into immutable, can you please explain what is going on and what you did to fix it?

**Comment by UnsungHero97** [comment]
Sure.

The old comparison was `m != oldM`, which makes sense conceptually ("are these values different?"), but it doesn't make sense in practice because `m` and `oldM` are objects, and more specifically, instances of `Immutable.Map`. If my interpretation of this bit of code is correct, then this is meant to check equality between two objects, and `!=` is not enough to make that decision.

Thankfully, `immutable-js`offers `.equals()`:

https://facebook.github.io/immutable-js/docs/#/Map/equals
https://facebook.github.io/immutable-js/docs/#/is

**Comment by luisrudge** [comment]
Great, thanks. Do you think we need to add another test for this case?

**Comment by UnsungHero97** [comment]
I don't know your codebase well enough, but from the little digging I did, it looks like `m` is guaranteed to be an instance of an `immutable-js` object, so `.equals()` should be available.

If there's test coverage for your use of `immutable-js`, then I think  we're safe. If not, it's probably a good idea to add tests to ensure we're working with `immutable-js` instances.

**Comment by luisrudge** [comment]
alright. thanks man! This will probably ship in the next release 🎉

**Comment by aautem** [comment]
Any update on this?

**Comment by luisrudge** [comment]
new pr: https://github.com/auth0/lock/pull/1091

Thanks @UnsungHero97 for fixing this and I'm super sorry we couldn't merge this before.

**Pull request closed without merging**
