### PR TITLE
Update fa.js

### PR DESCRIPTION
**Pull request by alirezagit**
Thank you for approving my previous contribution.
Now I fixed the rest of bugs in translation.
It's almost complete.

### CODE REVIEW

**Comment by stevehobbsdev** [comment]
Thanks @alirezagit. 

> It's almost complete.

We'd prefer to bring these changes into the library in one go.s the PR now complete or does it require further changes? If not, please mark the PR as a draft until such time it's ready for us to look at.

Thanks!

**Comment by alirezagit** [comment]
> If not, please mark the PR as a draft until such time it's ready for us to look at.


Thank you so much for responding
Unfortunately it isn't possible for me to check if these changes sit well on live preview of login page or not.
I have to wait and see how they will look like after being implemented.
For now I can say it is a correct and acceptable translation.
I mark it as draft.
Thanks a lot

**Comment by stevehobbsdev** [comment]
@alirezagit You could use [our playground](https://github.com/auth0/lock/blob/master/DEVELOPMENT.md#the-sdk-playground) to test those changes if you like. You'll need to configure the [playground script](https://github.com/auth0/lock/blob/master/support/index.html#L127) to use your locale so that they show up.

**Comment by alirezagit** [comment]
> @alirezagit You could use [our playground](https://github.com/auth0/lock/blob/master/DEVELOPMENT.md#the-sdk-playground) to test those changes if you like. You'll need to configure the [playground script](https://github.com/auth0/lock/blob/master/support/index.html#L127) to use your locale so that they show up.

Is there any way I can use my own language.js file from my own server with lock.min.js? Do I need to modify lock.min.js? That will be great if possible.

**Comment by stevehobbsdev** [comment]
You should be able to specify `languageBaseUrl` in the options to point Lock to a different host (including the scheme) for your translations. See [other options](https://github.com/auth0/lock/#other-options) in the Readme. So for example you might set `languageBaseUrl` like this:

```js
new Auth0Lock('client ID', 'domain', {
  languageBaseUrl: 'https://my-host.com'
});
```

Your languages files would have to be hosted such that the path is `<your host>/js/lock/<version>/fa.j` ([source](https://github.com/auth0/lock/blob/master/src/i18n.js#L80)).

**Comment by alirezagit** [comment]
> You should be able to specify `languageBaseUrl` in the options to point Lock to a different host (including the scheme) for your translations. See [other options](https://github.com/auth0/lock/#other-options) in the Readme. So for example you might set `languageBaseUrl` like this:
> 
> ```js
> new Auth0Lock('client ID', 'domain', {
>   languageBaseUrl: 'https://my-host.com'
> });
> ```
> 
> Your languages files would have to be hosted such that the path is `<your host>/js/lock/<version>/fa.j` ([source](https://github.com/auth0/lock/blob/master/src/i18n.js#L80)).

Thank you sir
You helped me a lot
💐💐💐

**Pull request closed without merging**
