### PR TITLE
added danish translation

### PR DESCRIPTION
**Pull request by carnevalle**

### CODE REVIEW

**Comment by pose** [comment]
@carnevalle Awesome! Tak

**Comment by carnevalle** [comment]
How do I then actually use this translation? I can see you have made a release after I added the translation, but it doesn't seem to exist in http://cdn.auth0.com/js/lock-6.8.2.min.js

**Comment by pose** [comment]
Have you checked our doc on [Lock i18n](https://github.com/auth0/lock/wiki/Auth0Lock-customization#dict-stringobject)? Thanks in advance

**Comment by carnevalle** [comment]
I hadn't included the translation in the dictionary. I have just created a new PR.

**Comment by pose** [comment]
Awesome, thanks!

**Pull request merged**
