### PR TITLE
XHTML compatibility fixes.

### PR DESCRIPTION
**Pull request by rafalwrzeszcz**
Fixed Lock to work with XHTML applications (`application/xhtml+xml` Content-Type).

### CODE REVIEW

**Comment by gnandretta** [comment]
@rafalwrzeszcz can you revert the changes from `&hellip;` to `&#8230;`? That way you can override the translations that are not compatible with xhtml and users who don't need that can still use `&hellip;`.

**Comment by rafalwrzeszcz** [comment]
Sure, I can - but `&#<code>;` notation works both in HTML and XHTML/XML, wouldn't it make more sense?

**Comment by rafalwrzeszcz** [comment]
Also - even though this PR makes JS library working with XHTML it's not the only problem. HTML produced by the backend for WS-Fed contains `<input>` tags (no closing `/>`).

I have a "dirty" fix for it locally, but it's not fixable on client-side in proper way, so I don't include it in this PR (I made a wrapper around `Auth0.prototype._renderAndSubmitWSFedForm` to do `String.replace()` on the param before invoking internal function).

**Comment by gnandretta** [comment]
Thank you.

**Pull request merged**
