### PR TITLE
Spelling mistake fixed

### PR DESCRIPTION
**Pull request by SebaAnhalt**
@luisrudge You are so fast ... :+1: The correct spelling in german is "E-Mail". Have a look at 
https://www.duden.de/rechtschreibung/E_Mail.

### CODE REVIEW

**Comment by luisrudge** [comment]
@SebaAnhalt thanks for the PR 🎉 is there a standardized way of writing Email in Germany? I ask this because in english it can be either email or e-mail. Google says both are fine: 
image

I guess my question is: Is E-mail your personal preference or is E-mail a standard in Germany?

**Comment by SebaAnhalt** [comment]
@luisrudge Is there a reason why you closed the branch without merging?

**Comment by luisrudge** [comment]
I asked a question and had no answer, so I closed the issue.

**Comment by SebaAnhalt** [comment]
@luisrudge Ah ... sorry my mistake. The answer is: "E-Mail" always with a hyphen. So the commit from me is correct.

**Pull request closed without merging**
