### PR TITLE
Last Update

### PR DESCRIPTION
**Pull request by jdunhin**
Hi

I really hope this is the last update. 

The fields i change is the signup. Teken in -> Registreer.

### CODE REVIEW

**Comment by jdunhin** [comment]
> I'm  so sorry. I think I misunderstood your comment. Please clone this project again and open a new PR so we don't have any conflicts in the files.

No it is my fault. I really hope this file is the correct one.

**Comment by luisrudge** [comment]
One question: Why are you changing the emailInputPlaceholder?

**Comment by jdunhin** [comment]
is it not just a string to translate? Else we can change it back to English

**Comment by luisrudge** [comment]
I mean, why did you change `Jou@voorbeeld.com` to `jou@epos.co.za`?

**Comment by jdunhin** [comment]
O, e-pos is Afrikaans for Email. And voorbeel(afr) is example(eng). So our project leader ask to change that.

**Comment by luisrudge** [comment]
ALright, so I'll rollback that so we keep it consistent with other translations (we use `example`). You can customize your own dictionary entries with the configuration options

**Comment by jdunhin** [comment]
Thank you all is good! I see that the lock version is //cdn.auth0.com/js/lock/10.18.0/lock.min.js in wordpress widget. i dont see changes, do i need to wait for next release? (it is not a problem to wait) again thank you for all your help.

**Comment by luisrudge** [comment]
Yes. This will be in the next release.

**Pull request merged**
