### PR TITLE
Lang Afrikaans South Africa

### PR DESCRIPTION
**Pull request by jdunhin**

### CODE REVIEW

**Comment by jdunhin** [comment]
any news when you will add this translation.

**Comment by luisrudge** [comment]
Can you rebase? I'll merge it asap

**Comment by jdunhin** [comment]
Hi, in advance sorry for dumb question. How do I push new update on file? lock/src/i18n/af.js

**Comment by luisrudge** [comment]
This pr was already closed. Please open another one if you want to send a correction

**Pull request merged**
