### PR TITLE
Adding focusable='false' to password SVG element

### PR DESCRIPTION
**Pull request by MaximRouiller**
Solves #741.

Might be necessary to review ALL svg.

### CODE REVIEW

**Comment by hzalaz** [comment]
@MaximRouiller thanks for the PR and the related issue. We'll send another PR setting focusable to all SVG just in case.

**Comment by MrPrashantT** [comment]
@MaximRouiller @hzalaz  which version of Lock has this been merged into?

**Comment by luisrudge** [comment]
@MrPrashantT here: https://github.com/auth0/lock/pull/873 - this will be in the next release

**Comment by MaximRouiller** [comment]
@MrPrashantT 

In the mid time, here are your options:

* you can either modify the source directly (do not recommend)
* you can do a fork on GitHub, apply the patch and use this (urghhh...)
* Monkey patch! Using jQuery, select all svg and add the attribute `focusable="false"` to all of them.

Most of the time, you won't want your SVG to have focus anyway. It's only IE who's a dirty dog in doing this. Let me know if I can help you further.

**Comment by luisrudge** [comment]
We just released a new version of lock with this fix. Thank you all for the patience!

**Pull request closed without merging**
