### PR TITLE
Update callback-cross-auth.html

### PR DESCRIPTION
**Pull request by aaguiarz**
Updated to v9.0.0 of auth0.js and used crossOriginVerification() function.

### CODE REVIEW

**Comment by VivekIshir** [comment]
@ aaguiarz  Hi , its not working for me , Could you please help me .

**Comment by luisrudge** [comment]
@VivekIshir what's not working?

**Comment by VivekIshir** [comment]
i am facing issue with cross Origin calling . we are redirecting URL on callback .

**Comment by luisrudge** [comment]
Hi, this doesn't look like a bug in the SDK. Please reach out to our amazing support team at https://support.auth0.com so they can better assist you with your scenario.

**Comment by VivekIshir** [comment]
@luisrudge okay .

**Pull request merged**
